FROM python:3.7.1

WORKDIR /web
ADD . /web
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME
EXPOSE 5000
EXPOSE 9000
CMD ["flask", "run"]
# CMD ["python","test_api.py"]
